### ISSUE TITLE
Status was present for previous strong-remoting

### ISSUE THREAD

**Issue by davidcheung** [strongloop/strong-error-handler#13]
https://github.com/strongloop/strong-remoting/blob/ac3093dcfbb787977ca0229b0f672703859e52e1/lib/rest-adapter.js#L394-L398

@bajtos do we want to preserve this behavior? 
it fails a couple of test cases, or should we update the test cases?
https://github.com/strongloop/loopback/blob/70cec0755acc2b670987675c3bc63ecbfe9b473f/test/relations.integration.js#L266
https://github.com/strongloop/loopback/blob/70cec0755acc2b670987675c3bc63ecbfe9b473f/test/relations.integration.js#L1655

**Comment by bajtos** [comment]
I think `statusCode` is more descriptive/accurate than `status`, let's use `statusCode` from now on and update test cases as necessary. Please mention this change in 3.0-RELEASE-NOTES.

**Comment by davidcheung** [comment]
agreed, closing this issue now
