### ISSUE TITLE
How to use in a non-express app?

### ISSUE THREAD

**Issue by squirrelsRduck** [strongloop/strong-error-handler#23]
Is this only compatible with express?

**Comment by davidcheung** [comment]
yes, 
for example it expects queries to be parsed into `req.query` https://github.com/strongloop/strong-error-handler/blob/613c7209d3a2c5d9d6d1c5bf6bbe8d14cbe89efe/lib/content-negotiation.js#L59

for now i believe the only code that is not compatible with `http-server`, but going forward there is possibility of more assumptions of it being an express app. 
@bajtos thoughts?

**Comment by bajtos** [comment]
Yes, this module is compatible with express only so far.

@squirrelsRduck What server are you using?

**Comment by squirrelsRduck** [comment]
regular node.js server, non-express, with loopback.

**Comment by squirrelsRduck** [comment]
Does that JSON in the readme cover all such setup if using Loopback?  Or is there some other config also required?

**Comment by davidcheung** [comment]
@squirrelsRduck oh, loopback is actually an express application, so yes it does work with strong-error-handler, the newest scaffolding in loopback 3.0 will use strong-error-handler, and strong-remoting 3.0 as well (for your endpoints). There are some notable changes (non-backwards compatible).

If you want the api endpoints to return errors to end-user using strong-error-handler the JSON in the readme would not cover that, you will need to use strong-error-handler in the restAdapter(strong-remoting) 
>Does that JSON in the readme cover all such setup if using Loopback

**Comment by squirrelsRduck** [comment]
@davidcheung ok, thanks.
