### ISSUE TITLE
Choosing language

### ISSUE THREAD

**Issue by celicoo** [strongloop/strong-error-handler#28]
Is it possible to use portuguese for the error messages?

Thanks!

**Comment by ssh24** [comment]
Hi @celicoo 

Yes, it is possible. Make sure to have your machine's primary language set to Portuguese. Once that is done, restart your terminal and try out any command which might give an error.

For example, try to create a loopback application with unexpected symbols on it:
```
? What's the name of your application? (%%^@%@%) 
>> O nome do aplicativo não pode conter caracteres especiais (/@+%: ): %%^@%@%
```

Please let me know if this answered your question.

**Comment by ssh24** [comment]
@celicoo Did you try fixing the issue with the way I specified?

**Comment by celicoo** [comment]
Hei @ssh24 , thanks for the help and i'm sorry for letting you wait! I dropped strongloop.

**Comment by ssh24** [comment]
Ok, closing this issue as a result of that.
