### ISSUE TITLE
Migration documentation confusion

### ISSUE THREAD

**Issue by loay** [strongloop/strong-error-handler#34]
The migration from express error handler to strong-error-handler is a bit confusing. It needs more careful review, and proper steps in order to ensure proper migration. 
The code snippets in the migration guide need to state when and where to be used.
What is the default option and what is a requirement and what is not. 

The ```handleErrors: false ``` part needs to be stated where and when to be used as well. 

CC:/ @superkhau @ritch @crandmck

**Comment by bajtos** [comment]
I am not sure if this is still relevant, see the discussion in #21 and https://github.com/strongloop/loopback-workspace/pull/372 which fixed the location of `handleErrors: false` in our project templates.

**Comment by loay** [comment]
The discussion in https://github.com/strongloop/strong-error-handler/issues/21 covered it
closing the issue.
