### ISSUE TITLE
Safefields doesn't work with "array of errors"

### ISSUE THREAD

**Issue by loopdtw** [strongloop/strong-error-handler#45]
### Description of feature (or steps to reproduce if bug)

Using loopback as an example, we can call POST with /users with an array of objects repeatedly such as below
```
[
  {
    "id": 1,
    "firstname": "Allen"
  },
  {
    "id": 2,
    "firstname": "Bob"
  }
]
```

with this middleware config:
```
"final:after": {
        "strong-error-handler": {
            "params": {
                "log": false,
                "safeFields": ["name", "message", "details"]
            }
        }
    }
```

### Expected result
```
{
  "error": {
    "statusCode": 500,
    "name": "ArrayOfErrors",
    "message": "Failed with multiple errors, see `details` for more information.",
    "details": [
      {
        "name": "Error",
        "message": "ER_DUP_ENTRY: Duplicate entry '2' for key 'PRIMARY'",
        "code": "ER_DUP_ENTRY",
        "errno": 1062,
        "sqlState": "23000",
        "index": 0
      },
      {
        "name": "Error",
        "message": "ER_DUP_ENTRY: Duplicate entry '3' for key 'PRIMARY'",
        "code": "ER_DUP_ENTRY",
        "errno": 1062,
        "sqlState": "23000",
        "index": 0,
      }
    ]
  }
}
```

### Actual result (if bug)
```
{
  "error": {
    "statusCode": 500
  }
}
```

### Additional information (Node.js version, LoopBack version, etc)
 "loopback": "^3.0.0",
 "strong-error-handler": "^1.0.1"

**Comment by SynerG** [comment]
Just in case, version 1.0.1 did not yet implement the 'safeFields' feature. So check that you really have a suitable version installed (version 1.2.1 includes the 'safeFields feature).
I haven't checked if this issue actually happens in 1.2.1 though.

**Comment by bajtos** [comment]
Hello, I agree this is a bug. I am afraid we don't have bandwidth to fix it ourself in the near future, would you like to contribute the patch yourself?

**Comment by IgorVanian** [comment]
2.2.0 not working aswell
