### ISSUE TITLE
Incorrect comment for negotiateContentProducer 

### ISSUE THREAD

**Issue by charlie-s** [strongloop/strong-error-handler#46]
### Description of feature (or steps to reproduce if bug)

`negotiateContentProducer` in `lib/content-negotiation.js` has its arguments in the incorrect order. It lists them in the comments as `req, options, logWarning` but in the signature as `req, logWarning, options`.

**Comment by bajtos** [comment]
@charlie-s thank you for reporting the problem. I think this is a great opportunity for new contributors to send their first pull request. Would you like to do that yourself?

**Comment by charlie-s** [comment]
Thanks bajtos, issued PR #49.
