### ISSUE TITLE
Add config option to log errors on a single line

### ISSUE THREAD

**Issue by sjawhar** [strongloop/strong-error-handler#63]
Currently, the stack trace is printed out on separate lines. When using Docker and a log aggregator, it results in one error being split across multiple lines. I believe by adding a config option (`logFormat`, maybe?, with possible values of `default` and `json`), this can all be condensed to a single line.

I plan to open a PR soon, if this idea is not abhorrent to anyone.

I will focus on this function. I will add a `format` argument to the function signature.
https://github.com/strongloop/strong-error-handler/blob/e1a0f5954f8cded5774c86dd86aba55383a22424/lib/logger.js#L11-L22

**Comment by bajtos** [comment]
@sjawhar thank you for the suggestion and sorry for not responding earlier. Our log format is intentionally kept rigid. Please use a custom error logging middleware if you want a different format of error log messages - see https://github.com/strongloop/strong-error-handler#customizing-log-format
