### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [strongloop/strong-error-handler#68]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature,

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by bajtos** [comment]
@Drulac thank you for the suggestion. How does your module handle HTML escaping of the dynamic values? (See https://github.com/strongloop/strong-error-handler/issues/66.)

To be honest, I am rather reluctant to use a new module that haven't been tested by time and usage.

**Comment by Drulac** [comment]
My module don't handle nothing, you should did it before inserting data into :-)

I understand
