### ISSUE TITLE
Safe fields can overwrite status code property

### ISSUE THREAD

**Issue by zbarbuto** [strongloop/strong-error-handler#71]
Safe fields introduced in #41 allow a `safeFields` array in options to copy properties from an error to the response payload in production mode.

If the `safeFields` array contains `statusCode`, then 500 type errors (which don't have a status code on them) will cause `undefined` to be copied to the response json payload, resulting in an undefined status code and an error from express.

Either the `statusCode` property needs to be special cased, or the `fillSafeFields` method needs to fallback to the existing properties in data if the given safe key is undefined in the error.

**Comment by bajtos** [comment]
The fix is available in `strong-error-handler@2.3.2`
