### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by shimks** [strongloop/strong-error-handler#75]
From #73 
- After the release:
 - Update places like `loopback-workspace` (both package.json and templates), `loopback-sanbox` to use the new major version of strong-error-handler.
 - The same applies to other dependents - `loopback` dev-dependencies, `strong-remoting` dev-dependencies, etc.

**Comment by dhmlau** [comment]
`3.0.0` is released.

**Comment by shimks** [comment]
closing as done
