### ISSUE TITLE
Duplicate fields status and statusCode on error json payload

### ISSUE THREAD

**Issue by mihir83in** [strongloop/strong-error-handler#80]
I am using swagger-express-middleware to validate incoming requests with loopback remote methods.
When swagger-express-middleware request-validator fails, it raises an error object with error.status being the response status code (i.e. 5xx, 4xx). 

The error is then propagated through strong-error-handler which fills in status code again through 

```
function fillStatusCode(data, err) {
  data.statusCode = err.statusCode || err.status;
  if (!data.statusCode || data.statusCode < 400)
    data.statusCode = 500;
}
```

the original error is then cloned in 

```
/**
 * clone the error properties to the data objects
 * [err.name,  err.message, err.stack] are not enumerable properties
 * @param data Object to be altered
 * @param err Error Object
 */
function cloneAllProperties(data, err) {
  data.name = err.name;
  data.message = err.message;
  for (var p in err) {
    if ((p in data)) continue;
    data[p] = err[p];
  }
  // stack is appended last to ensure order is the same for response
  data.stack = err.stack;
};
```

This results in payload that looks like : 

```
{
        "name": "Error",
        "message": "Missing required query parameter 'xxx'",
        "statusCode": 400,
        "status": 400
}
```
Additionally there are two functions namely `toJSON` and `stack` having stacktrace.

is there a way to address duplication of statuscode ?

is there a way to remove toJSON and stack from payload ?

I am on loopback 3.x version

**Comment by bajtos** [comment]
Hi @mihir83in, thank you for reporting these issues.

In general, I believe the behavior you are describing is exhibited only in the `debug` mode, where the handler tries to print as much information as possible to make troubleshooting easier.

Could you please confirm that the problem goes away when the debug mode is disabled?

> is there a way to address duplication of statuscode ?

I guess we can handle `status` and `statusCode` in a special way, and when they are both set to the same value, then we can omit `status` from the response. Would that solve the problem for you?

> is there a way to remove toJSON and stack from payload ?

`stack` is included intentionally to make errors easier to debug.

I am not sure why `toJSON` is included, this field is usually a function returning JSON representation of `this` object, and as such is skipped by `JSON.stringify`. Is this perhaps specific to `swagger-express-middleware`?

I would like to find a way how to remove `toJSON` in your use case, but I am very reluctant to add exceptions specific to 3rd party modules like `swagger-express-middleware`. Let's see if we can find a good way.
