### ISSUE TITLE
How can i get an single error message from loopback error body

### ISSUE THREAD

**Issue by ShubhamRK96** [strongloop/strong-error-handler#88]
I want that if any validation breaks, then it should break my code and return with proper error message.

I used inbuilt validation function as below:

```js
  Customer.validatesFormatOf('mobileno', {
    with: /^\+?([0-9]{2})\)?[-. ]?([0-9]{4})[-. ]?([0-9]{4})$/,
    message: 'Enter valid contact number'
  })

  Customer.validatesFormatOf('email', {
    with: /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/,
    message: 'Enter valid Email'
  })
```

I have tried this with promise and callbacks too but result is negative.

![image](https://user-images.githubusercontent.com/59476797/71725526-481cc200-2e5a-11ea-857d-5c8a827308ed.png)

I want that if my mobile no validation is true then only it will go for the email validation.

**Comment by bajtos** [comment]
@ShubhamRK96 IIUC, you would like to change the error message observed by your mobile application when calling LoopBack REST API, is that correct?

IMO, such transformation should be applied at the client side, inside your mobile application. LoopBack is providing a comprehensive error response with enough details to enable all kinds of clients to deal with the problem. Different clients require different information, I don't think it's feasible to deal with that on the server.

Having said that, if you don't like the error responses provided by `strong-error-handler`, you can configure your LoopBack application to use your own (custom) error handler instead. 

Just rework the `final:after` entry in `server/middleware.json` to use a different module. Learn more in our docs: [Defining middleware](https://loopback.io/doc/en/lb3/Defining-middleware.html).
